class Dream_Team_Constants:
    GOALKEEPER = 1
    MAX_GOALKEEPER = 1
    MIN_GOALKEEPER = 1
    DEFENDER = 2
    MAX_DEFENDER = 5
    MIN_DEFENDER = 3
    MIDFIELDER = 3
    MAX_MIDFIELDER = 5
    MIN_MIDFIELDER = 2
    STRIKER = 4
    MAX_STRIKER = 3
    MIN_STRIKER = 1
    OK = 0
    UNDERLOAD = 1
    OVERLOAD = 2
    HAS_ROOM = 3
    AT_MINIMUM = 4
